In [1]:
from modules.functions import run_linear_regression

In [2]:
help(run_linear_regression)

Help on function run_linear_regression in module modules.functions:

run_linear_regression(X, y)
    Run a linear regression.
    
    Parameters
    ----------
    X : Pandas DataFrame or numpy array of feature variables
    
    y : Pandas Series or numpy array of target variable
    
    Returns
    -------
    numpy array of predictions for the target variable , R**2 training score, R**2 testing score



In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [4]:
X = np.array([[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]])
y = np.array([1,2,3])

In [5]:
X

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [6]:
y

array([1, 2, 3])

In [7]:
y_pred, _, __ = run_linear_regression(X, y)

/Users/zacharyargentin/opt/anaconda3/envs/bootcamp/lib/python3.8/site-packages/sklearn/metrics/_regression.py:682: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)


In [8]:
y_pred

array([2., 2.])

In [9]:
from modules.functions import run_random_forest

In [10]:
run_random_forest(X, y)

train score = nan
test score = -9.0


/Users/zacharyargentin/opt/anaconda3/envs/bootcamp/lib/python3.8/site-packages/sklearn/metrics/_regression.py:682: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)


(array([1., 1.]), nan, -9.0)

In [11]:
from modules.functions import to_hours

In [23]:
s = pd.Series([0, 320, 2350, 2355, 2400]).round()

In [24]:
to_hours(s)

0     0.00
1     3.03
2    23.08
3    23.92
4     0.00
dtype: float64