In [1]:
from modules.functions import run_linear_regression

In [2]:
help(run_linear_regression)

Help on function run_linear_regression in module modules.functions:

run_linear_regression(X, y)
    Run a linear regression.
    
    Parameters
    ----------
    X : Pandas DataFrame or numpy array of feature variables
    
    y : Pandas Series or numpy array of target variable
    
    Returns
    -------
    R**2 score, numpy array of predictions for the target variable



In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [4]:
X = np.array([[1,2,3,4,5], [1,2,3,4,5], [1,2,3,4,5]])
y = np.array([1,2,3])

In [5]:
X

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [6]:
y

array([1, 2, 3])

In [7]:
r2, y_pred = run_linear_regression(X, y)

In [8]:
r2

0.0

In [9]:
y_pred

array([2., 2.])

In [10]:
from modules.functions import run_random_forest

In [11]:
run_random_forest(X, y)

train score = nan
test score = -9.0


/Users/zacharyargentin/opt/anaconda3/envs/bootcamp/lib/python3.8/site-packages/sklearn/metrics/_regression.py:682: UndefinedMetricWarning: R^2 score is not well-defined with less than two samples.
  warnings.warn(msg, UndefinedMetricWarning)


RandomForestRegressor(max_depth=5, n_estimators=50)